const actionTypes = {
  /*  PRODUCT ACTIONS START*/
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",
  /*  PRODUCT ACTIONS END*/
  // LOGIN ACTIONS START
  USER_LOGIN_REQUEST: "SER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  //LOGIN ACTIONS END
};

export default actionTypes;
